include ../../vep_0/share/make_common.mk

LIBNAME:= fifo
SOURCES:=$(wildcard libsrc/*.[cS])
CFLAGS += -I${SYSVEP}/libbsp/include/ -I$(SYSVEP)/tiles -Iinclude/

include ../../vep_0/share/make_library.mk
